### ISSUE TITLE
Finesse search homepage trigger a warning when accessed.

### ISSUE THREAD

**Issue by aakritimadaan** [ai-cfia/finesse-frontend#13]
Manually Build the container successfully. But when trying to test it locally with URL: localhost:3000, Finesse search (version: v0.1.0) Homepage has warning which is Initializing ping request to backend failed.
![Homepage error](https://github.com/ai-cfia/louis-finesse/assets/139572972/ffe59120-f967-408c-b4bc-a6dc9ec2ed40)

**Comment by k-allagbe** [comment]
I suggest pinging the `/health` or `/` route on the backend instead of the `/search` route.
