### ISSUE TITLE
Integrate a Debug Panel for Simulated Response Data and Add Test Case for HighlightedContent

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/finesse-frontend#18]
#### Overview:
In our ongoing efforts to streamline the development process and improve testing, we've integrated a debug panel into the frontend. This panel allows developers to toggle the use of simulated response data, eliminating the need for a backend server during specific stages of frontend development. The simulated data is sourced from a `testData.json` file.

#### Details:
1. **Debug Panel Implementation:** A debug panel has been added to the frontend, which provides an interface to toggle between using live data from the backend server and simulated data from a JSON file.
2. **Data Source:** The simulated data is pulled from a `testData.json` file, making it easy for developers to adjust the dataset as needed for various testing scenarios.
3. **Search Results Integration:** When the debug panel's toggle is active, search results are populated using the simulated data. This ensures a seamless experience that closely mirrors the live data environment, even without an active backend.

#### Future Work:
1. **Test Case Requirement:** While we've made significant progress on the simulated data integration, there's a need for a test case around the `HighlightedContent` component. Specifically, we should ensure the `highlightWords` function correctly returns highlighted indices for the first data item from the `testData.json`. This test will help verify the accuracy of the highlighting functionality, ensuring it behaves consistently across both simulated and live data scenarios.

**Recommendations**:
- Fast-track the development of the test case for the `HighlightedContent` component to ensure stability and consistency in the feature.
- Review and expand `testData.json` as needed to simulate various data scenarios and edge cases.
- Provide documentation or an onboarding guide for new developers to understand the purpose and usage of the debug panel.

**Comment by k-allagbe** [comment]
This seems already done. https://github.com/ai-cfia/finesse-frontend/pull/20
