### ISSUE TITLE
Enhance Data Flexibility in Debug Panel

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/finesse-frontend#22]
#### Problem:
Currently, our system only processes specific test data at build time. This limitation restricts our ability to simulate and test different scenarios, especially during the debugging phase.

#### Suggestion:
To increase flexibility, I propose we incorporate a text field within the debug panel. This text field would allow for the input of JSON data, which the system can then use for testing purposes. 

By making this change, we can readily adjust the test data without having to rebuild or reconfigure the system. This will expedite the testing process, especially when working with diverse datasets.

#### Benefits:
- **Flexibility:** Allows for rapid changes to test data without a rebuild.
- **Efficiency:** Facilitates a smoother and quicker debugging process.
- **Customizability:** Enables the testing of different scenarios or use cases by merely adjusting the input data.

#### Proposed Implementation:
1. Introduce a text field in the debug panel.
2. Set it with some reasonable default samples to begin with.
3. Ensure the system can parse and use the provided JSON data from this text field.

**Comment by k-allagbe** [comment]
We moved away from this requirement. We now fetch the files from `finesse-data`. Closing this.
