### ISSUE TITLE
Update `postCreateCommand` in React TypeScript project

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/finesse-frontend#25]
### Description:
In our React TypeScript project, we currently have the following `postCreateCommand`:

"postCreateCommand": "npm install -g npm@9.8.1 --force",

We need to modify it to also include the installation of @saithodev/ts-appversion.

#### Proposed Change:

Update the postCreateCommand as follows:

"postCreateCommand": "npm install -g npm@9.8.1 --force && npm i @saithodev/ts-appversion"

Acceptance Criteria:

    Ensure the global npm version (9.8.1) is installed successfully.
    Ensure the @saithodev/ts-appversion package is installed in the project.

**Comment by k-allagbe** [comment]
https://github.com/ai-cfia/finesse-frontend/blob/fd032516d0fec92e534d25f5b2a17733f4fb264d/package.json#L6

It seems that we already install @saithodev/ts-appversion via `package.json`. If this issue is actually a necessary step, I suggest mentioning the reason.
