### ISSUE TITLE
Add deployment to vercel for finesse-frontend

### ISSUE THREAD

**Issue by redat97** [ai-cfia/finesse-frontend#38]
The deployment to vercel is need to be able to test one of the workflow that has been created but will also allow the ability to test deployment to a different URL so that user aren't affect in the event of a deployment that isn't fully functionnal

**Comment by rngadam** [comment]
We need to have a bit more consistent documentation on our environments. 

Any production-level app (with real users) should be deployed to three environment:

- dev: whatever is on main at the moment
- uat: frozen to allow for users to test before we push to production
- prd: production version

this naming is also part of the conversation in the naming ADR with @JolanThomassin 

https://github.com/ai-cfia/dev-rel-docs/pull/77

**Comment by redat97** [comment]
> We need to have a bit more consistent documentation on our environments.
> 
> Any production-level app (with real users) should be deployed to three environment:
> 
> * dev: whatever is on main at the moment
> * uat: frozen to allow for users to test before we push to production
> * prd: production version
> 
> this naming is also part of the conversation in the naming ADR with @JolanThomassin
> 
> [ai-cfia/dev-rel-docs#77](https://github.com/ai-cfia/dev-rel-docs/pull/77)

Vercel allows for different stages which I think is something that could be useful. it's as simple as adding -- env-name to the deploy command, we could have all the different stages inside vercel and have the prod as github pages. Just a suggestion

**Comment by rngadam** [comment]
> > We need to have a bit more consistent documentation on our environments.
> > Any production-level app (with real users) should be deployed to three environment:
> > 
> > * dev: whatever is on main at the moment
> > * uat: frozen to allow for users to test before we push to production
> > * prd: production version
> > 
> > this naming is also part of the conversation in the naming ADR with @JolanThomassin
> > [ai-cfia/dev-rel-docs#77](https://github.com/ai-cfia/dev-rel-docs/pull/77)
> 
> Vercel allows for different stages which I think is something that could be useful. it's as simple as adding -- env-name to the deploy command, we could have all the different stages inside vercel and have the prod as github pages. Just a suggestion

yes. document environment management in the devops repo.

**Comment by redat97** [comment]
@rngadam I think I was wrong, doing further research it's not possible to depoy to different envrionment using the CLI, because of the -dev flag I thought that refered to development stages, it is possible if you connect your github to have different URL deployment based on the branch but I am not sure it's something that would be acceptable since that means directly connecting the project to vercel.

![Screenshot_54](https://github.com/ai-cfia/finesse-frontend/assets/9827730/e9c587cb-2264-4eba-8731-7203826d7049)

There are two options I can think of if we don't want to do that, we could have 3 different website hosting plateform assigning each one to a specific stage, or we could have only two which would be Vercel and gh-pages and use vercel's preview URL as the first stage, this is the preview URL for one of the deployment I made
[finesse-frontend-fywxp3pq3-reda-tarzalts-projects.vercel.app](https://vercel.com/reda-tarzalts-projects/finesse-frontend/Cuzjk4FRzTxJP3cm5fMfShCgb2Ce)
and then have the main vercel URL as the second stage which would look like this
[finesse-frontend.vercel.app](https://finesse-frontend.vercel.app/)
and have github pages be the final stage

**Comment by rngadam** [comment]
> There are two options I can think of if we don't want to do that,

https://vercel.com/docs/cli/deploy#deploying-to-a-custom-domain

> In the following example, you create a bash script that you include in your CI/CD  workflow. The goal is to have all preview deployments be aliased to a custom domain so that developers can bookmark the preview deployment URL.


if I read it correctly, you can get vercel deploy to auto-generate a url that you can then alias to the right environment.

    vc alias $deploymentUrl finesse-frontend-dev.vercel.com

or

    vc alias $deploymentUrl finesse-frontend-uat.vercel.com

or 

    vc alias $deploymentUrl finesse-frontend-prd.vercel.com

**Comment by redat97** [comment]
> > There are two options I can think of if we don't want to do that,
> 
> https://vercel.com/docs/cli/deploy#deploying-to-a-custom-domain
> 
> > In the following example, you create a bash script that you include in your CI/CD  workflow. The goal is to have all preview deployments be aliased to a custom domain so that developers can bookmark the preview deployment URL.
> 
> if I read it correctly, you can get vercel deploy to auto-generate a url that you can then alias to the right environment.
> 
> ```
> vc alias $deploymentUrl finesse-frontend-dev.vercel.com
> ```
> 
> or
> 
> ```
> vc alias $deploymentUrl finesse-frontend-uat.vercel.com
> ```
> 
> or
> 
> ```
> vc alias $deploymentUrl finesse-frontend-prd.vercel.com
> ```

ah it's to map the preview url to the desired URL didn't think about that option I only researched about how to deploy directly to the URL makes sense I will look into it

**Comment by redat97** [comment]
> > There are two options I can think of if we don't want to do that,
> 
> https://vercel.com/docs/cli/deploy#deploying-to-a-custom-domain
> 
> > In the following example, you create a bash script that you include in your CI/CD  workflow. The goal is to have all preview deployments be aliased to a custom domain so that developers can bookmark the preview deployment URL.
> 
> if I read it correctly, you can get vercel deploy to auto-generate a url that you can then alias to the right environment.
> 
> ```
> vc alias $deploymentUrl finesse-frontend-dev.vercel.com
> ```
> 
> or
> 
> ```
> vc alias $deploymentUrl finesse-frontend-uat.vercel.com
> ```
> 
> or
> 
> ```
> vc alias $deploymentUrl finesse-frontend-prd.vercel.com
> ```

just a heads up, .com is taken so it's .app
[finesse-frontend-dev.vercel.app](https://finesse-frontend-dev.vercel.app/)

**Comment by ThomasCardin** [comment]
Won't do. We will preview deployment when this issue (https://github.com/ai-cfia/infra/issues/20) will be solved (iteration 3). No more maintenance time will be put into Vercel
