### ISSUE TITLE
FR: Display version and commit head in the frontend

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/finesse-frontend#4]
Testing will require a version of sort to track what version of the source test plans execution are made against. 

So we want to insert commit and package.json version and display it in the frontend.

There seems to be tools to be able to do this as part of the build process:

https://github.com/saitho/ts-appversion

**Comment by k-allagbe** [comment]
Done in https://github.com/ai-cfia/finesse-frontend/pull/6. Closing.
