### ISSUE TITLE
Move lint-tests for finesse-frontend to vercel deployment

### ISSUE THREAD

**Issue by redat97** [ai-cfia/finesse-frontend#51]
The lint-tests are currently in the gh-pages deployment workflow but they should be moves to vercel for better consistency since that workflow is triggered on every push. Also, since it's not clear if we will continue using gh-pages or what is going to be our production web host, it will make it easier to just remove the gh-pages wokflow if we decide to move away from that option rather than having to add the lint-tests to another workflow

**Comment by rngadam** [comment]
I don't understand this issue and why you're removing the lint-test before github pages or trying to push the lint-test in the reusable workflow for deployment workflows. Or getting rid of Github Pages, which could still be useful in some scenarios.

As it-is, this works:

* Github pages deployment
  * lint-test reusable workflow
  * deploy to Github Page using Github page reusable workflow
 * Vercel deployment
   * lint-test workflow
   * deploy to vercel  using Vercel reusable workflow

 don't want lint-test to be happening twice? 

I would think you can also create dependencies between workflows local to the repo:
   
* lint-test.yml
* Github pages deployment
  * needs[lint-test]
  * deploy to Github Page using Github page reusable workflow
 * Vercel deployment
   * needs[lint-test]
   * deploy to vercel  using Vercel reusable workflow

**Comment by redat97** [comment]
> I don't understand this issue and why you're removing the lint-test before github pages or trying to push the lint-test in the reusable workflow for deployment workflows. Or getting rid of Github Pages, which could still be useful in some scenarios.
> 
> As it-is, this works:
> 
> * Github pages deployment
>   
>   * lint-test reusable workflow
>   * deploy to Github Page using Github page reusable workflow
> * Vercel deployment
>   
>   * lint-test workflow
>   * deploy to vercel  using Vercel reusable workflow
> 
> don't want lint-test to be happening twice?
> 
> I would think you can also create dependencies between workflows local to the repo:
> 
> * lint-test.yml
> * Github pages deployment
>   
>   * needs[lint-test]
>   * deploy to Github Page using Github page reusable workflow
> * Vercel deployment
>   
>   * needs[lint-test]
>   * deploy to vercel  using Vercel reusable workflow

but in what case does the deployment to gh-pages occurs? push to main like for uat?

**Comment by rngadam** [comment]
> but in what case does the deployment to gh-pages occurs? push to main like for uat?

I want the option to continue deploying to Github Pages and the option to deploy to Vercel. 

It doesn't have to be for finesse-frontend, but I don't want to be in a situation we're we rely on a single static pages deployment solution or where the CI/CD is specific to one platform.

**Comment by redat97** [comment]
> > but in what case does the deployment to gh-pages occurs? push to main like for uat?
> 
> I want the option to continue deploying to Github Pages and the option to deploy to Vercel.
> 
> It doesn't have to be for finesse-frontend, but I don't want to be in a situation we're we rely on a single static pages deployment solution or where the CI/CD is specific to one platform.

I am really confused, did you not say to remove the github pages deployment in the last phrase https://github.com/ai-cfia/finesse-frontend/pull/45#discussion_r1415485044 or I misunderstood?

**Comment by rngadam** [comment]
> I am really confused, did you not say to remove the github pages deployment in the last phrase [#45 (comment)](https://github.com/ai-cfia/finesse-frontend/pull/45#discussion_r1415485044) or I misunderstood?

I'll explain it to you next time we talk

**Comment by ThomasCardin** [comment]
Won't do. We will preview deployment when this issue (https://github.com/ai-cfia/infra/issues/20) will be solved (iteration 3). No more maintenance time will be put into Vercel
