### ISSUE TITLE
As a developper, I would like to redirect the previous gh pages to the new one. I also want to remove the gh pages deployment once this is done

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/finesse-frontend#72]
- [ ] Step 1: Redirect https://ai-cfia.github.io/nachet-frontend/ to https://nachet.ninebasetwo.xyz
- [ ] Step 2: Remove the gh pages deployment.
    - Soon enough we will be cross-cloud with 3 instances of this deployment

**Comment by rngadam** [comment]
if your step 2 is to remove the old URL, then anyone referencing that old URL will face a 404. Best to keep the page up with redirection until we've ensured no traffic goes through this URL.
