### ISSUE TITLE
Access Blocked

### ISSUE THREAD

**Issue by nmeraihi** [ai-cfia/finesse-frontend#73]
When accessing from work cell phone, the web page is blocked.
`Web Page Blocked

You have tried to access a web page that is in violation of your Internet usage policy. `
![image](https://github.com/ai-cfia/finesse-frontend/assets/12937961/c42ea471-b38d-4bb5-80e3-070c5800ad32)
_not sure FE or BE issue_

**Comment by rngadam** [comment]
@nmeraihi this is not related to the application but a policy on mobile phones to block newly discovered, external domain. Would need to file a ticket with internal IT support. 

Although it is probably not worth it as that domain is only temporary (and we don't test for mobile at the moment).
