### ISSUE TITLE
Fix markdown line length errors

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/finesse-frontend#82]
Upon creating an integration pipeline to analyze markdown linting on the repository, the following [errors](https://github.com/ai-cfia/finesse-frontend/pull/80/files) have surfaced : 
![image](https://github.com/ai-cfia/finesse-frontend/assets/73133692/64452b41-5b99-4763-ab22-30ff62f2a0a2)

**Comment by rngadam** [comment]
You can break a long line with URL by using the line continuation with parenthesis:

```
Refer to our comprehensive [Design and UX Philosophy documentation](
https://github.com/ai-cfia/dev-rel-docs/blob/91-document-design-philosophy-and-ux-concept/Design-UX/DESIGN-UX-PHILOSOPHY.md) for a detailed guide on our approach
```

Will still display as a single line:

Refer to our comprehensive [Design and UX Philosophy documentation](
https://github.com/ai-cfia/dev-rel-docs/blob/91-document-design-philosophy-and-ux-concept/Design-UX/DESIGN-UX-PHILOSOPHY.md) for a detailed guide on our approach

Please update the relevant documentation.

**Comment by ibrahim-kabir** [comment]
This issue is no longer observed

**Comment by rngadam** [comment]
> This issue is no longer observed

The last line of my latest comment is to **Please update the relevant documentation.**

**Comment by ibrahim-kabir** [comment]
> > This issue is no longer observed
> 
> @ibrahim-kabir The last line of my latest comment is to **Please update the relevant documentation.**

Done, check the finesse channel to find the documentation.
